# Generated by Django 4.2.13 on 2026-04-13 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('store', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('electronics', 'Electronics'), ('appliances', 'Appliances'), ('furniture', 'Furniture'), ('clothing', 'Clothing'), ('vehicles', 'Vehicles'), ('tools', 'Tools & Hardware'), ('jewelry', 'Jewelry & Watches'), ('other', 'Other')], default='other', max_length=50)),
                ('purchase_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('warranty_end', models.DateField()),
                ('notes', models.TextField(blank=True, default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='receipts/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Receipt',
                'verbose_name_plural': 'Receipts',
                'ordering': ['-created_at'],
            },
        ),
    ]
